[package]
name = "trash"
version = "0.1.0"
authors = ["Cauê Baasch de Souza <cauebs@pm.me>"]
edition = "2018"
license = "GPL-3.0+"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
